### PR TITLE
Added Contributing file, added html section, and progress resources.

### PR DESCRIPTION
**Pull request by NS007-dev**
@Ayan-thecodeking , I added:

- [x] CONTRIBUTING.md file, with file how to contribute.
- [x] I added a HTML resource section.
- [x] I added in progress resources.

Thank you.

### CODE REVIEW

**Comment by NS007-dev** [comment]
Is it possible for me to have access to the full repo please? This is because so I am able to add templates in issues, complete the website, and add a github action, that will add all the contributors, every time someone contributes. Thanks.

**Comment by NS007-dev** [comment]
Any Updates @Ayan-thecodeking thank you.

**Comment by Ayan-thecodeking** [comment]
> Is it possible for me to have access to the full repo please? This is because so I am able to add templates in issues, complete the website, and add a github action, that will add all the contributors, every time someone contributes. Thanks.

sry I haven't looked your PR ....and if you want to add templates and github action add it ,you can also create PRs and i'll merge it that would be more better

**Comment by Ayan-thecodeking** [comment]
> Any Updates @Ayan-thecodeking thank you.

good work :)

**Comment by NS007-dev** [comment]
> > Is it possible for me to have access to the full repo please? This is because so I am able to add templates in issues, complete the website, and add a github action, that will add all the contributors, every time someone contributes. Thanks.
> 
> sry I haven't looked your PR ....and if you want to add templates and github action add it ,you can also create PRs and i'll merge it that would be more better

thank you.

**Pull request merged**
